### ISSUE TITLE
[scanner] NPM - wrong git repo blocks the scan

### ISSUE THREAD

**Issue by fb33** [heremaps/oss-review-toolkit#2077]
Hello

I run ORT on windows with git bash in admin mode.
The scanner seems to be stuck on the npm dependency : camel-case:3.0.0
I run the scan twice and each times the process "freeze" on this dependency. (check the stdout below)
the camel-case is special use-case because the git repository has been rename, so the url https://github.com/blakeembrey/camel-case.git return 404.
Is there an issue with http code management ?

```
Summary:        info, licenses, copyrights with 7 process(es)
Errors count:   0
Scan Speed:     0.23 files/sec. 80.13 Bytes/sec.
Initial counts: 11 resource(s): 10 file(s) and 1 directorie(s)
Final counts:   10 resource(s): 10 file(s) and 0 directorie(s) for 3.39 KB
Timings:
  scan_start: 2019-12-21T184839.748000
  scan_end:   2019-12-21T184926.356000
  setup_scan:licenses: 3.25s
  setup: 3.25s
  scan: 43.29s
  total: 46.62s
Removing temporary files...done.

19:49:27.487 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'D:\Users\j.dupont\AppData\Local\Temp\ort18384322399870562749ScanCode-3.0.2\scancode-toolkit-3.0.2\scancode.bat --version' in 'C:\workspace\POCs\MOB_ORT\oss-review-toolkit'...
19:49:33.378 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture - ScanCode version 3.0.2
19:49:33.378 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture -
19:49:33.378 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture -
19:49:33.392 [ScanCode-1] INFO  com.here.ort.scanner.storages.FileBasedStorage - Stored scan result for 'NPM::caller-path:2.0.0' at path 'NPM/unknown/caller-path/2.0.0/scan-results.yml'.
19:49:33.393 [ScanCode-1] INFO  kotlinx.coroutines.CoroutineScope - Finished scanning NPM::caller-path:2.0.0 (135/1618).
19:49:33.393 [ScanCode-1] INFO  kotlinx.coroutines.CoroutineScope - No stored results found, scanning package NPM::camel-case:3.0.0 in thread 'ScanCode-1' (138/1618).
19:49:33.393 [ScanCode-1] INFO  com.here.ort.downloader.Downloader - Trying to download source code for 'NPM::camel-case:3.0.0'.
19:49:33.394 [ScanCode-1] INFO  com.here.ort.downloader.Downloader - Trying to download 'NPM::camel-case:3.0.0' sources to 'C:\workspace\POCs\MOB_ORT\my-gateway-web\client\reports\downloads\NPM\unknown\camel-case\3.0.0' from VCS...
19:49:33.395 [ScanCode-1] INFO  com.here.ort.downloader.Downloader - Using processed VcsInfo(type=Git, url=https://github.com/blakeembrey/camel-case.git, revision=719ebc39a5bf828f794db64bb1a78c8dd8fef133, resolvedRevision=null, path=). Original was VcsInfo(type=Git, url=git://github.com/blakeembrey/camel-case.git, revision=719ebc39a5bf828f794db64bb1a78c8dd8fef133, resolvedRevision=null, path=).
19:49:33.395 [ScanCode-1] INFO  com.here.ort.downloader.Downloader - Detected VCS type 'Git' from type name 'Git'.
19:49:33.405 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git --version' in 'C:\workspace\POCs\MOB_ORT\oss-review-toolkit'...
19:49:33.458 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture - git version 2.21.0.windows.1
19:49:33.458 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture -
19:49:33.460 [ScanCode-1] INFO  com.here.ort.downloader.VersionControlSystem - Using Git version 2.21.0.windows.1.
19:49:33.469 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git init' in 'C:\workspace\POCs\MOB_ORT\my-gateway-web\client\reports\downloads\NPM\unknown\camel-case\3.0.0'...
19:49:33.630 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture - Initialized empty Git repository in C:/workspace/POCs/MOB_ORT/my-gateway-web/client/reports/downloads/NPM/unknown/camel-case/3.0.0/.git/
19:49:33.630 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture -
19:49:33.640 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git remote add origin https://github.com/blakeembrey/camel-case.git' in 'C:\workspace\POCs\MOB_ORT\my-gateway-web\client\reports\downloads\NPM\unknown\camel-case\3.0.0'...
19:49:33.722 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git --version' in 'C:\workspace\POCs\MOB_ORT\oss-review-toolkit'...
19:49:33.771 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture - git version 2.21.0.windows.1
19:49:33.771 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture -
19:49:33.782 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git config protocol.version 2' in 'C:\workspace\POCs\MOB_ORT\my-gateway-web\client\reports\downloads\NPM\unknown\camel-case\3.0.0'...
19:49:33.856 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git config core.longpaths true' in 'C:\workspace\POCs\MOB_ORT\my-gateway-web\client\reports\downloads\NPM\unknown\camel-case\3.0.0'...
19:49:33.928 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git status -sb --porcelain=v2' in 'C:\workspace\POCs\MOB_ORT\my-gateway-web\client\reports\downloads\NPM\unknown\camel-case\3.0.0'...
19:49:34.004 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture - # branch.oid (initial)
19:49:34.004 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture - # branch.head master
19:49:34.004 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture -
19:49:34.015 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git remote show -n' in 'C:\workspace\POCs\MOB_ORT\my-gateway-web\client\reports\downloads\NPM\unknown\camel-case\3.0.0'...
19:49:34.073 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture - origin
19:49:34.073 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture -
19:49:34.084 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'git -c credential.helper= -c core.askpass=echo ls-remote --refs origin refs/heads/*' in 'C:\workspace\POCs\MOB_ORT\my-gateway-web\client\reports\downloads\NPM\unknown\camel-case\3.0.0'...
```

regards

**Comment by sschuberth** [comment]
I remember that we had issues like this under Windows before (see e.g. 0f07ac138ee9f6ce737d7f8bbc89fed21e128775 or 449d958be8e24ed5411e757dd07f802f8c9c03e6). The underlying problem likely is that Git cannot distinguish whether a GitHub repo really does not exist, or if it is just not accessible due to missing authentication. I'll probably look into rewriting the Git code with jgit to finally solve this.

**Comment by fb33** [comment]
Is there a way to configure ORT to skip some dependencies ?

**Comment by sschuberth** [comment]
There's something better yet: You could create a [curation](https://github.com/heremaps/oss-review-toolkit/blob/master/docs/config-file-curations-yml.md) that points ORT to the correct location for the source code repository.

**Comment by fb33** [comment]
Ok, I'll try with curation.
Thanks

**Comment by fb33** [comment]
Hello,

I add a curation file and re-run the analyzer.
Then I run the scanner and I'm no more stuck on camel-case ! thanks :-)

But... 

Now I ve got a  java.nio.file.AccessDeniedException, like in the .Net context https://github.com/heremaps/oss-review-toolkit/issues/2072#issue-540829562

```
Summary:        info, licenses, copyrights with 7 process(es)
Errors count:   0
Scan Speed:     0.26 files/sec. 618.94 Bytes/sec.
Initial counts: 13 resource(s): 10 file(s) and 3 directorie(s)
Final counts:   12 resource(s): 10 file(s) and 2 directorie(s) for 23.20 KB
Timings:
  scan_start: 2019-12-23T162259.833000
  scan_end:   2019-12-23T162342.740000
  setup_scan:licenses: 4.41s
  setup: 4.41s
  scan: 38.39s
  total: 42.93s
Removing temporary files...done.

17:23:46.376 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'D:\Users\j.dupont\AppData\Local\Temp\ort13901306789589718462ScanCode-3.0.2\scancode-toolkit-3.0.2\scancode.bat --version' in 'C:\workspace\POCs\MOB_ORT\oss-review-toolkit'...
17:23:51.665 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture - ScanCode version 3.0.2
17:23:51.665 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture -
17:23:51.665 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture -
17:23:51.669 [ScanCode-1] INFO  com.here.ort.scanner.storages.FileBasedStorage - Could not read scan results for 'NPM::extsprintf:1.3.0' from path 'NPM/unknown/extsprintf/1.3.0/scan-results.yml': FileNotFoundException: D:\Users\j.dupont\.ort\scanner\results\NPM\unknown\extsprintf\1.3.0\scan-results.yml (Le chemin d▒acc▒s sp▒cifi▒ est introuvable)
17:23:51.734 [ScanCode-1] INFO  com.here.ort.scanner.storages.FileBasedStorage - Stored scan result for 'NPM::extsprintf:1.3.0' at path 'NPM/unknown/extsprintf/1.3.0/scan-results.yml'.
17:23:51.734 [ScanCode-1] INFO  kotlinx.coroutines.CoroutineScope - Finished scanning NPM::extsprintf:1.3.0 (392/1618).
Exception in thread "main" java.nio.file.AccessDeniedException: C:\workspace\POCs\MOB_ORT\my-gateway-web\client-reports\downloads\NPM\unknown\ext\1.4.0\.git\objects\pack\pack-855252e0e77ebf49aace01f22e6772d2e7bc7c04.idx
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:270)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
        at java.base/java.nio.file.Files.delete(Files.java:1141)
        at com.here.ort.utils.ExtensionsKt$safeDeleteRecursively$1.visitFile(Extensions.kt:141)
        at com.here.ort.utils.ExtensionsKt$safeDeleteRecursively$1.visitFile(Extensions.kt:128)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
        at com.here.ort.utils.ExtensionsKt.safeDeleteRecursively(Extensions.kt:128)
        at com.here.ort.utils.ExtensionsKt.safeDeleteRecursively$default(Extensions.kt:121)
        at com.here.ort.downloader.Downloader.download(Downloader.kt:175)
        at com.here.ort.downloader.Downloader.download$default(Downloader.kt:129)
        at com.here.ort.scanner.LocalScanner.scanPackage(LocalScanner.kt:287)
        at com.here.ort.scanner.LocalScanner.access$scanPackage(LocalScanner.kt:75)
        at com.here.ort.scanner.LocalScanner$scanPackages$2$invokeSuspend$$inlined$map$lambda$1$4.invokeSuspend(LocalScanner.kt:195)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by sschuberth** [comment]
> I add a curation file and re-run the analyzer.
> Then I run the scanner and I'm no more stuck on camel-case ! thanks :-)

That's great to hear. While you can still reproduce the original issue, could you maybe check whether it also appears (without your curation) with the `vcs-jgit` branch, which partly uses JGit already?

**Comment by sschuberth** [comment]
> Now I ve got a java.nio.file.AccessDeniedException, like in the .Net context [#2072 (comment)](https://github.com/heremaps/oss-review-toolkit/issues/2072#issue-540829562)

Indeed, that code path also needs `force = true` on Windows, thanks. Fixed in https://github.com/heremaps/oss-review-toolkit/pull/2079.

**Comment by fb33** [comment]
I just test with `vcs-jgit` branch with an analyser-results without curation.
this branch resolve the problem of wrong git repo, no stuck on camel-case.
but, I still have a java.nio.file.AccessDeniedException

```
Scanning done.
Summary:        info, licenses, copyrights with 7 process(es)
Errors count:   0
Scan Speed:     1.37 files/sec. 3.13 KB/sec.
Initial counts: 59 resource(s): 50 file(s) and 9 directorie(s)
Final counts:   58 resource(s): 50 file(s) and 8 directorie(s) for 114.46 KB
Timings:
  scan_start: 2019-12-23T225219.403000
  scan_end:   2019-12-23T225300.048000
  setup_scan:licenses: 4.01s
  setup: 4.01s
  scan: 36.52s
  total: 40.69s
Removing temporary files...done.

23:53:01.679 [ScanCode-1] INFO  com.here.ort.utils.ProcessCapture - Running 'D:\Users\j.dupont\AppData\Local\Temp\ort14210244974063322228ScanCode-3.0.2\scancode-toolkit-3.0.2\scancode.bat --version' in 'C:\workspace\POCs\MOB_ORT\oss-review-toolkit'...
23:53:05.462 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture - ScanCode version 3.0.2
23:53:05.463 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture -
23:53:05.463 [ScanCode-1] DEBUG com.here.ort.utils.ProcessCapture -
23:53:05.467 [ScanCode-1] INFO  com.here.ort.scanner.storages.FileBasedStorage - Could not read scan results for 'NPM::extglob:2.0.4' from path 'NPM/unknown/extglob/2.0.4/scan-results.yml': FileNotFoundException: D:\Users\j.dupont\.ort\scanner\results\NPM\unknown\extglob\2.0.4\scan-results.yml (Le chemin d▒acc▒s sp▒cifi▒ est introuvable)
23:53:05.484 [ScanCode-1] INFO  com.here.ort.scanner.storages.FileBasedStorage - Stored scan result for 'NPM::extglob:2.0.4' at path 'NPM/unknown/extglob/2.0.4/scan-results.yml'.
23:53:05.484 [ScanCode-1] INFO  kotlinx.coroutines.CoroutineScope - Finished scanning NPM::extglob:2.0.4 (391/1618).
Exception in thread "main" java.nio.file.AccessDeniedException: C:\workspace\POCs\MOB_ORT\my-gateway-web\client-reports\downloads\NPM\unknown\ext\1.4.0\.git\objects\pack\pack-855252e0e77ebf49aace01f22e6772d2e7bc7c04.idx
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:270)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
        at java.base/java.nio.file.Files.delete(Files.java:1141)
        at com.here.ort.utils.ExtensionsKt$safeDeleteRecursively$1.visitFile(Extensions.kt:141)
        at com.here.ort.utils.ExtensionsKt$safeDeleteRecursively$1.visitFile(Extensions.kt:128)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
        at com.here.ort.utils.ExtensionsKt.safeDeleteRecursively(Extensions.kt:128)
        at com.here.ort.utils.ExtensionsKt.safeDeleteRecursively$default(Extensions.kt:121)
        at com.here.ort.downloader.Downloader.download(Downloader.kt:175)
        at com.here.ort.downloader.Downloader.download$default(Downloader.kt:129)
        at com.here.ort.scanner.LocalScanner.scanPackage(LocalScanner.kt:287)
        at com.here.ort.scanner.LocalScanner.access$scanPackage(LocalScanner.kt:75)
        at com.here.ort.scanner.LocalScanner$scanPackages$2$invokeSuspend$$inlined$map$lambda$1$4.invokeSuspend(LocalScanner.kt:195)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

Mery Xmas !

**Comment by sschuberth** [comment]
> I just test with `vcs-jgit` branch with an analyser-results without curation.
> this branch resolve the problem of wrong git repo, no stuck on camel-case.

Great, thanks again for checking!

> but, I still have a java.nio.file.AccessDeniedException

Yes, for that one to be resolved you *additionally* need my `more-vcs-cleanup-force` branch merged.

> Mery Xmas !

Thanks, to you, too!

**Comment by fb33** [comment]
Hi,

I continue my tests with the `more-vcs-cleanup-force` branch.
After few iterations to update the curation file, I've finally ended the scanner step and go on with evaluator and reporter.

But I still have some troubles.

First at the end of scanner, I found some errors (217 exactly) in the scan-result.yml.
205 like this :
```   message: "Could not scan 'NPM:@xtuc:long:4.2.2' (1618/1618): ScanException:\
              \ Running 'D:\\Users\\j.dupont\\AppData\\Local\\Temp\\ort12273197390833416137ScanCode-3.0.2\\\
              scancode-toolkit-3.0.2\\scancode.bat --copyright --license --ignore\
              \ *.ort.yml --info --strip-root --timeout 300 --ignore HERE_NOTICE --ignore\
              \ META-INF/DEPENDENCIES --processes 7 --license-diag --verbose C:\\\
              workspace\\POCs\\MOB_ORT\\my-gateway-web\\client-reports\\downloads\\\
              NPM\\%40xtuc\\long\\4.2.2 --json-pp C:\\workspace\\POCs\\MOB_ORT\\my-gateway-web\\\
              client-reports\\native-scan-results\\NPM\\%40xtuc\\long\\4.2.2\\scan-results_ScanCode.json'\
              \ in 'C:\\workspace\\POCs\\MOB_ORT\\oss-review-toolkit' failed with\
              \ exit code 2:\nUsage: scancode [OPTIONS] <input> <OUTPUT FORMAT\n\n\
              \                OPTION(s)>\n\nTry 'scancode --help' for help on options\
              \ and arguments.\n\n\n\nError: Invalid value for \"input\": Path \"\
              C:\\workspace\\POCs\\MOB_ORT\\my-gateway-web\\client-reports\\\
              downloads\\NPM\\0xtuc\\long\\4.2.2\" does not exist.\n\n"
            severity: "ERROR"
```
and 12 like :
```	
	message: "Could not scan 'NPM::write:1.0.3' (1395/1618): ScanException:\
              \ Running 'D:\\Users\\j.dupont\\AppData\\Local\\Temp\\ort12273197390833416137ScanCode-3.0.2\\\
              scancode-toolkit-3.0.2\\scancode.bat --copyright --license --ignore\
              \ *.ort.yml --info --strip-root --timeout 300 --ignore HERE_NOTICE --ignore\
              \ META-INF/DEPENDENCIES --processes 7 --license-diag --verbose C:\\\
              workspace\\POCs\\MOB_ORT\\my-gateway-web\\client-reports\\downloads\\\
              NPM\\unknown\\write\\1.0.3 --json-pp C:\\workspace\\POCs\\MOB_ORT\\\
              my-gateway-web\\client-reports\\native-scan-results\\NPM\\unknown\\\
              write\\1.0.3\\scan-results_ScanCode.json' in 'C:\\workspace\\POCs\\\
              MOB_ORT\\oss-review-toolkit' failed with exit code 1:\n Setup plugin:\
              \ output:json-pp...\n\n Setup plugin: pre_scan:ignore...\n\n Setup plugin:\
              \ scan:info...\n\n Setup plugin: scan:copyrights...\n\n Setup plugin:\
              \ scan:licenses...\n\nCollect file inventory...\n\nRun pre-scans...\n\
              \n Run pre-scan: ignore...\n\nScan files for: info, licenses, copyrights\
              \ with 7 process(es)...\n\nScanned: C:\\workspace\\POCs\\MOB_ORT\\my-gateway-web\\\
              client-reports\\downloads\\NPM\\unknown\\write\\1.0.3\\.editorconfig\n\
              Scanned: C:\\workspace\\POCs\\MOB_ORT\\my-gateway-web\\client-reports\\\
              downloads\\NPM\\unknown\\write\\1.0.3\\.eslintrc.json\n[...skipping\
              \ 23 lines...]\n  File \"D:\\Users\\j.dupont\\AppData\\Local\\Temp\\\
              ort12273197390833416137ScanCode-3.0.2\\scancode-toolkit-3.0.2\\lib\\\
              site-packages\\click\\decorators.py\", line 17, in new_func\n    return\
              \ f(get_current_context(), *args, **kwargs)\n  File \"d:\\users\\j.dupont\\\
              appdata\\local\\temp\\ort12273197390833416137scancode-3.0.2\\scancode-toolkit-3.0.2\\\
              src\\scancode\\cli.py\", line 752, in scancode\n    quiet=quiet, verbose=verbose,\
              \ kwargs=kwargs,\n  File \"d:\\users\\j.dupont\\appdata\\local\\temp\\\
              ort12273197390833416137scancode-3.0.2\\scancode-toolkit-3.0.2\\src\\\
              scancode\\cli.py\", line 929, in run_scanners\n    with_timing=timing,\
              \ progress_manager=progress_manager)\n  File \"d:\\users\\j.dupont\\\
              appdata\\local\\temp\\ort12273197390833416137scancode-3.0.2\\scancode-toolkit-3.0.2\\\
              src\\scancode\\cli.py\", line 1075, in scan_codebase\n    pool.terminate()\n\
              \  File \"c:\\python27\\Lib\\multiprocessing\\pool.py\", line 470, in\
              \ terminate\n    self._terminate()\n  File \"c:\\python27\\Lib\\multiprocessing\\\
              util.py\", line 207, in __call__\n    res = self._callback(*self._args,\
              \ **self._kwargs)\n  File \"c:\\python27\\Lib\\multiprocessing\\pool.py\"\
              , line 518, in _terminate_pool\n    p.terminate()\n  File \"c:\\python27\\\
              Lib\\multiprocessing\\process.py\", line 140, in terminate\n    self._popen.terminate()\n\
              \  File \"c:\\python27\\Lib\\multiprocessing\\forking.py\", line 312,\
              \ in terminate\n    _subprocess.TerminateProcess(int(self._handle),\
              \ TERMINATE)\nWindowsError: [Error 5] Acc�s refus\n\n(Above output is\
              \ limited to each 20 heading and tailing lines.)"
```	

For the first 205 errors, it seems to be a problem of encode/decode url.
The directory that is searched is `C:\workspace\POCs\MOB_ORT\my-gateway-web\client-reports\downloads\NPM\0xtuc\long\4.2.2\`
But the directory that was created is `C:\workspace\POCs\MOB_ORT\my-gateway-web\client-reports\downloads\NPM\%40xtuc\long\4.2.2\`
%40 is for the `@` char, no ?

For the 15 others, it seems to be like initial `java.nio.file.AccessDeniedException` but with this branch, that doesn't break the scanner process and "just" trace the error in the result file.


Secondly, the reporter generate a scan-report-web-app.html that doesn't work.
The web page stucks at 25% of the processing result data.
For information, the scanner-result.yml and the evaluation-result.yml are about 100Mo (the magic of npm ! ;-) ) and the scan-report-web-app.html is about 50Mo

**Comment by sschuberth** [comment]
Just a quick note: Regarding the "WindowsError: [Error 5] Access is refused / denied", there's a fix / work-around pending for that [in ScanCode](https://github.com/nexB/scancode-toolkit/issues/1670#issuecomment-524255865), however that fix is not in a released version of ScanCode yet.

**Comment by sschuberth** [comment]
The original issue of non-existing GitHub repos blocking the scan on Windows is now fixed in *master* as https://github.com/heremaps/oss-review-toolkit/pull/2081 has been merged. Also, the follow-up issue with another `AccessDeniedException` is fixed in *master* now, see https://github.com/heremaps/oss-review-toolkit/pull/2079.

Regarding any remaining issues, please open separate reports for each of them, even if they occurred during the same scan. Just two quick comments:

- ORT percent-encodes package paths to avoid invalid characters being used on file systems.
- If you face issues with loading the web-app report in Firefox, please try Chrome instead.
